project:
  type: website
  output-dir: docs

website:
  title: "T.H.Lin"
  navbar:
    left:
      - href: notes.qmd
        text: Notes

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



